apiVersion: v1
kind: Service
metadata:
  name: nginx-projet01
  labels:
    app: nginx-projet01
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      # nodePort: 30008
  selector:
    app: nginx-projet01